export const ACCOUNT_REPOSITORY = Symbol('ACCOUNT_REPOSITORY');
export const CATEGORY_REPOSITORY = Symbol('CATEGORY_REPOSITORY');
export const TRANSACTION_REPOSITORY = Symbol('TRANSACTION_REPOSITORY');
export const BUDGET_REPOSITORY = Symbol('BUDGET_REPOSITORY');
export const EVENT_PUBLISHER = Symbol('EVENT_PUBLISHER');
